apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 5
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
      #annotations:
       # sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: reservation
          image: 467263215646.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser16-reservation:v1
          # 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-product:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              #memory: "20Mi"
              cpu: "200m" # 1/5 core
            limits:
              #memory: "40Mi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: '/reservations'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
